project:
  type: website
  output-dir: "_site"

date-format: iso

format-links: false

format:
  html:
    code-copy: true
    code-overflow: wrap
    include-in-header:
      - _includes/anchor-icon-fix.html
      - _includes/auto-color-scheme.html
      - _includes/hatena-nocomment.html
    linestretch: 1.4
    respect-user-color-scheme: true
    # https://quarto.org/docs/output-formats/html-themes.html
    theme:
      light:
        - yeti
        - themes/font.scss
      dark:
        - solar
        - themes/font.scss
    toc-depth: 2
    toc-expand: 2
    toc: true
  gfm: default

website:
  title: "uma-chan's page"
  bread-crumbs: true
  description: "All of my thoughts."
  favicon: "assets/common/icon_hhkb3.png"
  google-analytics: "GOOGLE_ANALYTICS_PLACEHOLDER"
  image: "assets/common/icon_hhkb3_large.jpg"
  navbar:
    background: secondary
    search: true
    left:
      - text: "Blog"
        href: "blog/index.qmd"
      - text: "Zenn"
        href: "zenn/index.qmd"
      - text: "Slides"
        href: "slides/index.qmd"
      - text: "Resume"
        href: "resume/index.qmd"
    # right:
    #   - icon: github
    #     href: "https://github.com/i9wa4"
    #   - icon: twitter-x
    #     href: "https://x.com/i9wa4_"
    #   - icon: linkedin
    #     href: "https://www.linkedin.com/in/daikm"
    #   - icon: rss
    #     href: "blog/index.xml"
  open-graph:
    locale: "ja_JP"
    site-name: "uma-chan's page"
  twitter-card:
    card-style: summary_large_image
    creator: "@i9wa4_"
    site: "@i9wa4_"
  page-footer:
    left:
      - text: "&copy; 2024-YEAR_PLACEHOLDER uma-chan"
    right:
      - icon: github
        href: "https://github.com/i9wa4"
      - icon: twitter-x
        href: "https://x.com/i9wa4_"
      - icon: linkedin
        href: "https://www.linkedin.com/in/daikm"
      - icon: rss
        href: "blog/index.xml"
      - text: "Built with"
      - text: "Quarto"
        href: "https://quarto.org/"
  search: true
  site-url: "https://i9wa4.github.io"
