project:
  type: website
  output-dir: "_site"
  render:
    - "**/*.qmd"
    - "!*.md"

date-format: iso

execute:
  freeze: auto

format-links: true

format:
  html:
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    include-in-header:
      - _includes/hatena-nocomment.html
      - _includes/anchor-icon-fix.html
    linestretch: 1.4
    page-layout: full
    # https://quarto.org/docs/output-formats/html-themes.html
    theme:
      light:
        - yeti
        - themes/font.scss
      dark:
        - darkly
        - themes/font.scss
    toc-depth: 2
    toc-expand: 2
    toc: true
  gfm: default

website:
  title: "uma-chan's page"
  bread-crumbs: false
  favicon: "assets/common/icon_hhkb3.png"
  google-analytics: "GOOGLE_ANALYTICS_PLACEHOLDER"
  image: "assets/common/icon_hhkb3_large.jpg"
  repo-actions: [source, issue]
  repo-url: "https://github.com/i9wa4/i9wa4.github.io"
  search: true
  site-url: "https://i9wa4.github.io"
  open-graph:
    locale: "ja_JP"
    site-name: "uma-chan's page"
  twitter-card:
    card-style: summary_large_image
    creator: "@i9wa4_"
    site: "@i9wa4_"
  page-footer:
    left:
      - text: "&copy; 2024-YEAR_PLACEHOLDER uma-chan"
    right:
      - text: "Built with"
      - text: "Quarto"
        href: "https://quarto.org/"
  sidebar:
    style: floating
    tools:
      - icon: github
        href: "https://github.com/i9wa4"
      - icon: twitter-x
        href: "https://x.com/i9wa4_"
      - icon: linkedin
        href: "https://www.linkedin.com/in/daikm"
      - icon: rss
        href: "index.xml"
    contents:
      - href: "index.qmd"
        text: "Top"
      - text: "---"
      - section: "Content"
        contents:
          - href: "blog/index.qmd"
            text: "Blog"
          - href: "slides/index.qmd"
            text: "Slides"
          - href: "resume/index.qmd"
            text: "Resume"
          - href: "about.qmd"
            text: "About"
