[tools]
# Package managers
uv = "0.9.17"

# Development tools
gitleaks = "8.30.0"
pre-commit = "4.5.0"
shellcheck = "0.11.0"

# Aqua tools
"aqua:JohnnyMorganz/StyLua" = "2.3.1"
"aqua:rhysd/actionlint" = "1.7.9"
"aqua:suzuki-shunsuke/pinact" = "3.6.0"
"aqua:zizmorcore/zizmor" = "1.18.0"
