[project]
name = "i9wa4-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.14.0"
dependencies = [
  "numpy",
  "pandas",
  "playwright",
  "quarto-cli",
]

[dependency-groups]
dev = [
  "pyyaml",
  "ruff",
]
